### ISSUE TITLE
0.9.0 checklist

### ISSUE THREAD

**Issue by misund** [dbmedialab/shiny#599]
- [x] start theme (#589)
- [x] color box overflow (#598)
- [x] proper css reset (#584)
- [x] dependency updates
- [ ] does not break tests
